# -*- coding: utf-8 -*-
"""arvorebinaria

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tsGtQ3LfT3Pxlba3w-73PfZNZeN3Gj68
"""

class No:
    def __init__(self, valor):
        self.valor = valor
        self.esquerda = None
        self.direita = None

class ArvoreBinaria:
    def __init__(self):
        self.raiz = None

    def inserir(self, valor):
        if self.raiz is None:
            self.raiz = No(valor)
        else:
            self._inserir_recursivo(valor, self.raiz)

    def _inserir_recursivo(self, valor, no):
        if valor < no.valor:
            if no.esquerda is None:
                no.esquerda = No(valor)
            else:
                self._inserir_recursivo(valor, no.esquerda)
        elif valor > no.valor:
            if no.direita is None:
                no.direita = No(valor)
            else:
                self._inserir_recursivo(valor, no.direita)

dados_arvore = [200, 450, 123, 52, 133, 321, 422, 523, 36, 64]

arvore = ArvoreBinaria()
for valor in dados_arvore:
    arvore.inserir(valor)