# -*- coding: utf-8 -*-
"""pilhaefila

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tsGtQ3LfT3Pxlba3w-73PfZNZeN3Gj68
"""

class Pilha:
    def __init__(self):
        self.itens = []

    def empilhar(self, item):
        self.itens.append(item)

    def desempilhar(self):
        if not self.esta_vazia():
            return self.itens.pop()

    def esta_vazia(self):
        return len(self.itens) == 0

class Fila:
    def __init__(self):
        self.itens = []

    def enfileirar(self, item):
        self.itens.append(item)

    def desenfileirar(self):
        if not self.esta_vazia():
            return self.itens.pop(0)

    def esta_vazia(self):
        return len(self.itens) == 0

dados = [64, 25, 12, 22, 11, 9]

pilha = Pilha()
for item in dados:
    pilha.empilhar(item)

fila = Fila()
for item in dados:
    fila.enfileirar(item)